import type { ApiConfig, DefaultSearchPreferences, NormalizedJob } from "@/lib/types";

export const STORAGE_KEYS = {
  apiConfig: "jobpulse.apiConfig",
  connectionStatus: "jobpulse.connectionStatus",
  recentSearches: "jobpulse.recentSearches",
  preferences: "jobpulse.preferences",
};

export const DEFAULT_API_CONFIG: ApiConfig = {
  adzunaAppId: "",
  adzunaAppKey: "",
  openSkillsBaseUrl: "",
  country: "us",
  useDemoMode: true,
};

export const DEFAULT_PREFERENCES: DefaultSearchPreferences = {
  keyword: "software engineer",
  location: "Chicago, IL",
  remoteOnly: false,
};

export const DEMO_JOBS: NormalizedJob[] = [
  {
    id: "demo-1",
    title: "Software Engineer II",
    company: "North Harbor Systems",
    location: "Chicago, IL",
    salaryMin: 105000,
    salaryMax: 135000,
    salaryText: "$105,000 - $135,000",
    createdAt: new Date().toISOString(),
    createdAtLabel: "Today",
    redirectUrl: "https://example.com/jobs/1",
    source: "demo",
    category: "Engineering",
    contractType: "full_time",
  },
  {
    id: "demo-2",
    title: "Data Analyst",
    company: "Cedar Ridge Health",
    location: "Remote (US)",
    salaryMin: 80000,
    salaryMax: 98000,
    salaryText: "$80,000 - $98,000",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    createdAtLabel: "1 day ago",
    redirectUrl: "https://example.com/jobs/2",
    source: "demo",
    category: "Data",
    contractType: "full_time",
  },
  {
    id: "demo-3",
    title: "Product Manager",
    company: "Summit Ledger",
    location: "Austin, TX",
    salaryMin: null,
    salaryMax: null,
    salaryText: "Salary not listed",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    createdAtLabel: "2 days ago",
    redirectUrl: "https://example.com/jobs/3",
    source: "demo",
    category: "Product",
    contractType: "full_time",
  },
  {
    id: "demo-4",
    title: "Frontend Engineer",
    company: "North Harbor Systems",
    location: "Chicago, IL",
    salaryMin: 110000,
    salaryMax: 145000,
    salaryText: "$110,000 - $145,000",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    createdAtLabel: "3 days ago",
    redirectUrl: "https://example.com/jobs/4",
    source: "demo",
    category: "Engineering",
    contractType: "full_time",
  },
  {
    id: "demo-5",
    title: "Business Intelligence Engineer",
    company: "Cedar Ridge Health",
    location: "Remote (US)",
    salaryMin: 95000,
    salaryMax: 125000,
    salaryText: "$95,000 - $125,000",
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    createdAtLabel: "4 days ago",
    redirectUrl: "https://example.com/jobs/5",
    source: "demo",
    category: "Data",
    contractType: "full_time",
  },
];
